name: build

on:
  - push
  - pull_request

jobs:
  test:
    name: "Test: Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1, 3.2, 3.3, 3.4, jruby]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cache-version: 1
      - name: Ruby Version
        run: ruby --version
      - name: Bundle Install with Retry (fallback)
        if: failure()
        run: |
          echo "Bundler cache failed, retrying bundle install..."
          for i in {1..3}; do
            if bundle install --jobs 4 --retry 3; then
              break
            fi
            echo "Bundle install attempt $i failed, retrying in 10 seconds..."
            sleep 10
          done
      - name: Run Tests
        run: bundle exec rake
