name: build

on:
  - push
  - pull_request

jobs:
  test:
    name: "Test: Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0, 3.1, 3.2.6, jruby]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Ruby Version
        run: ruby --version
      - name: Run Tests
        run: bundle exec rake
